### ISSUE TITLE
"sudo dnf copr enable seeitcoming/rcm" errors out

### ISSUE THREAD

**Issue by BKStephens** [thoughtbot/rcm#176]
I am trying out Korora 23 in a VM, and I receive the following output from "sudo dnf copr enable seeitcoming/rcm"

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dnfpluginscore/lib.py", line 71, in urlopen
    librepo.download_url(url, fo.fileno(), handle)
  File "/usr/lib64/python3.4/site-packages/librepo/__init__.py", line 1517, in download_url
    return _librepo.download_url(handle, url, fd)
librepo.LibrepoException: (10, 'Status code: 404 for https://copr.fedorainfracloud.org/coprs/seeitcoming/rcm/repo/epel-23/', 'Error HTTP/FTP status code')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dnf-plugins/copr.py", line 264, in _download_repo
    f = dnfpluginscore.lib.urlopen(self, None, self.copr_url + api_path, 'w+')
  File "/usr/lib/python3.4/site-packages/dnfpluginscore/lib.py", line 73, in urlopen
    raise IOError(e.args[1])
OSError: Status code: 404 for https://copr.fedorainfracloud.org/coprs/seeitcoming/rcm/repo/epel-23/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/dnf", line 57, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.4/site-packages/dnf/cli/main.py", line 174, in user_main
    errcode = main(args)
  File "/usr/lib/python3.4/site-packages/dnf/cli/main.py", line 60, in main
    return _main(base, args)
  File "/usr/lib/python3.4/site-packages/dnf/cli/main.py", line 112, in _main
    cli.run()
  File "/usr/lib/python3.4/site-packages/dnf/cli/cli.py", line 1095, in run
    return self.command.run(self.base.extcmds)
  File "/usr/lib/python3.4/site-packages/dnf-plugins/copr.py", line 153, in run
    self._download_repo(project_name, repo_filename, chroot)
  File "/usr/lib/python3.4/site-packages/dnf-plugins/copr.py", line 272, in _download_repo
    res = urllib.request.urlopen(self.copr_url + "/coprs/" + project_name, 'w+')
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 461, in open
    req = meth(req)
  File "/usr/lib64/python3.4/urllib/request.py", line 1112, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
```

**Comment by mike-burns** [comment]
I'm not entirely sure who made this package, so I don't know who to ping on this one. Do you know?

**Comment by BKStephens** [comment]
Looking at https://copr.fedorainfracloud.org/coprs/seeitcoming/ and the committers for this repo, I can see seeitcoming has the same profile picture as @supervacuo

**Comment by supervacuo** [comment]
Hi, yes, it was me!

This looks like a problem with Korora; I hit their website to find out how it was even using `dnf` (distro was gentoo-based last time I looked...) and their latest blog post is "When Adding a COPR repo to Korora Fails":

> Unfortunately the command provided on the COPR site does not work on Fedora remixes such as Korora. The command attempts to determine the version and arch you are running but doesn't recognise a remix

> $ sudo dnf copr enable reponame fedora-23-x86_64

**Comment by supervacuo** [comment]
fix it, for glittering imaginary internet point prizes:

- edit `rcm`'s README to document this workaround **(1 point)**
- verify if it's actually a problem with `dnf` **(4 points)**
- make sure a bug report is filed wherever it belongs **(10 points)**
- patch `dnf` to handle Fedora Remixes correctly **(50 points)**
- wait for me to do one of the above **(0 points ☺)**

**Comment by BKStephens** [comment]
Thanks for finding [that](https://kororaproject.org/about/news/when-adding-a-copr-repo-to-korora-fails)! I just tried the workaround, and it works:
```
sudo dnf copr enable seeitcoming/rcm fedora-23-x86_64
```
@mike-burns Would you accept a PR to add Korora instructions to the Installation section of the README?

**Comment by mike-burns** [comment]
I'd love to PR to add Korora instructions to the README.
